AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.0
  FrozenStringLiteral: true
  Exclude:
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'

require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3
