openapi: 3.0.0
info:
  title: Bitcoin API Rest
  description: Documentation of Bitcoin API endpoints
  version: 1.0.0
paths:
  /login:
    post:
      tags:
        - sessions
      summary: Log in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password
      responses:
        '200':
          description: login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'login successful'

  /logout:
    delete:
      tags:
        - sessions
      summary: Log out
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'logged out successfully'
  /users:
    post:
      tags:
        - users
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: password
                password_confirmation:
                  type: string
                  example: password
      responses:
        '200':
          description: user created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'user created successfuly'
  /users/:user-id/wallets:
    get:
      tags:
        - wallets
      summary: Get all user wallets
      responses:
        '200':
          description: List of user wallets
  /users/:user-id/wallets/usd/credit:
    post:
      tags:
        - wallets
      summary: Credit wallet in USD
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 100
      responses:
        '200':
          description: Funds credited successfully
  /users/:user-id/wallets/btc/credit:
    post:
      tags:
        - wallets
      summary: Credit wallet in BTC
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  example: 0.00001
      responses:
        '200':
          description: Funds credited successfully
  /users/:user-id/transactions:
    get:
      tags:
        - transactions
      summary: Get all user transactions
      responses:
        '200':
          description: List of user transactions
    post:
      tags:
        - transactions
      summary: Create transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currency_sent:
                  type: string
                  example: USD
                currency_received:
                  type: string
                  example: BTC
                amount_sent:
                  type: number
                  example: 100
      responses:
        '200':
          description: Transaction created successfully
  /users/:user-id/transactions/{transaction-id}:
    get:
      tags:
        - transactions
      summary: Get specific transaction
      parameters:
        - name: transaction-id
          in: path
          required: true
          description: ID of the transaction 
          schema:
            type: string
      responses:
        '200':
          description: Details of the requested transaction
  /bitcoin_price:
    get:
      tags:
        - bitcoin price
      summary: Get current Bitcoin price
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  bitcoin_price:
                    type: string
                    example: '1 bitcoin is equal to 51457.744 USD'
